[workspace]
members = [
    "cassandra-protocol",
    "cdrs-tokio",
    "cdrs-tokio-helpers-derive"
]

[workspace.dependencies]
arc-swap = "1.5.0"
uuid = "1.0.0"
derivative = "2.2.0"
derive_more = "0.99.17"
bytes = "1.1.0"
itertools = "0.11.0"
thiserror = "1.0.31"
