[package]
name = "cdrs-tokio"
version = "6.0.0-beta.3"
authors = ["Alex Pikalov <alex.pikalov.khar@gmail.com>", "Kamil Rojewski <kamil.rojewski@gmail.com>"]
edition = "2018"
description = "Async Cassandra DB driver written in Rust"
documentation = "https://docs.rs/cdrs-tokio"
homepage = "https://github.com/krojew/cdrs-tokio"
repository = "https://github.com/krojew/cdrs-tokio"
readme = "../README.md"
keywords = ["cassandra", "driver", "client", "cassandradb", "async"]
license = "MIT/Apache-2.0"

[features]
default = ["v4"]
rust-tls = ["rustls", "tokio-rustls", "webpki"]
v3 = ["cassandra-protocol/v3"]
v4 = ["cassandra-protocol/v4"]
# enable v5 feature when it's actually implemented
# v5 = ["cassandra-protocol/v5"]
e2e-tests = []

[dependencies]
arc-swap ="1.4"
atomic = "0.5"
bytes = "1.1"
derive_more = "0.99"
float_eq = "0.6"
futures = { version = "0.3", default_features = false, features = ["alloc"] }
fxhash = "0.2"
lz4_flex = "0.8"
itertools = "0.10"
rand = "0.8"
serde_json = "1.0"
tokio = { version = "1", features = ["net", "io-util", "rt", "sync", "macros", "rt-multi-thread", "time"] }
tokio-rustls = { version = "0.22", optional = true }
tracing = "0.1"
uuid = "0.8"
webpki = { version = "0.21", optional = true }
cassandra-protocol = { path = "../cassandra-protocol", version = "1.0.0--beta.1" }

[dependencies.rustls]
version = "0.19"
optional = true
default-features = false

[dev-dependencies]
cdrs-tokio-helpers-derive = { path = "../cdrs-tokio-helpers-derive", version = "3.2.0-beta.1" }
maplit = "1.0.0"
mockall = "0.10"
lazy_static = "1.4"
regex = "1.5"
uuid = { version = "0.8", features = ["v4"] }
time = { version = "0.3", features = ["std", "macros"] }
